// Thai and English source wording is retained. Photograph filenames provide provenance.
const practiceIntro = `<p>กรุณาตรวจสอบและทบทวน<a href="#module-2/2">คำแนะนำของโปรเจคต์</a>ให้มั่นใจก่อนเริ่มทำคำถามฝึกหัดนี้ หลังจากคำถามฝึกหัดเหล่านี้แล้ว ในหน้าถัดไปคุณจะพบกับคำถามทดสอบความรู้จริงที่จะมีการเก็บคะแนน (สำหรับส่วนนี้ คุณจะต้องเขียน Justification ด้วยตัวเอง ไม่ใช่ข้อสอบแบบปรนัย) ซึ่งคะแนนตรงนี้จะเป็นตัวตัดสินว่าคุณจะผ่านเกณฑ์เข้าร่วมทำงานในโปรเจคต์ S2S บน Aether หรือไม่ ขอบคุณครับ!</p><p>กรุณาตั้งใจฟังคลิปเสียงทั้งสองคลิปอย่างละเอียด</p><p>โดยทั้งสองคลิปเป็นการตอบกลับคำสั่ง (Prompt) เดียวกันจากผู้ใช้</p>`;
const practiceQuestion = `คลิปไหนเหมาะสมกับเกณฑ์ "North Star" ของโปรเจคต์ในภาพรวมมากกว่ากัน? กรุณาเลือกคำอธิบายเหตุผล (Justification) ที่ถูกต้องและละเอียดที่สุดจากตัวเลือกด้านล่าง ซึ่งมีการปรับใช้ลำดับความสำคัญของโปรเจคต์อย่างชัดเจน : Naturalness & Engagement / Aesthetics > Utility > Audio Quality`;
const practiceRequirements = `<p>โดยคำตอบที่ถูกต้องจะต้องอธิบายครอบคลุมประเด็นต่อไปนี้</p><ol><li>คลิปไหนดีกว่าในภาพรวม</li><li>ทำไมคลิปที่ชนะถึงดีกว่าเมื่อเทียบตามลำดับความสำคัญ (Hierarchy)</li><li>ทำไมอีกคลิปถึงไม่ควรชนะ เพียงเพราะว่าเสียงดูคลีนกว่าหรือตอบได้ครบถ้วนกว่า</li><li>มีคลิปใดที่มีปัญหาด้าน Audio หรือ Utility จนเกือบตกเกณฑ์มาตรฐาน (Threshold-level) หรือไม่</li></ol>`;
export const module2 = [
  {id:'s2s-welcome',title:'Aether S2S Quality Screener - TH',section:'Aether S2S Quality Screener - TH',kind:'reading',sources:['20261007_130216.jpg'],html:`<div class="course-welcome"><div class="course-icon" aria-hidden="true">☀</div><h2>Aether S2S Quality Screener - TH</h2><p>หลักสูตรนี้ จะมีการทดสอบระบบเสียงสเตอริโอของหูฟังของท่าน ก่อนการเข้าทำงานในโปรเจค Live S2S ภายใต้ Aether Multilingual นอกจากนี้ท่านควรศึกษาขั้นตอนการทำงาน ลำดับความสำคัญของการให้คะแนน คุณภาพของเสียง และข้อผิดพลาดที่มักพบได้บ่อย ขอให้ท่านโชคดีในการทำคอร์ส</p><p><span class="time-badge">25 mins</span></p><a class="button primary" href="#module-2/2">Start Course</a></div>`},
  {id:'s2s-overview',title:'Project Overview',section:'Project Overview',kind:'reading',sources:['20261007_130321.jpg','20261007_130333.jpg','20261007_130344.jpg','20261007_130358.jpg','20261007_130406.jpg'],html:`
<p><mark><strong>ข้อควรทราบสำคัญเกี่ยวกับคอร์สนี้:</strong></mark> คำแนะนำและตัวอย่างในคอร์สนี้จะจัดทำขึ้นเป็นภาษาไทย</p>
<p><strong>ในการทำงานจริงสำหรับ S2S</strong> หากคุณผ่านคอร์สนี้แล้ว หน้าต่างคำแนะนำบน UI ของระบบจะเป็นภาษาอังกฤษ <strong class="source-warning">และคุณจำเป็นต้องเขียน Justification เป็นภาษาอังกฤษ</strong>ด้วย แต่สำหรับการสนทนาระหว่างคุณกับ Voice Model จะใช้ ภาษาไทย</p>
<p>ในการทดสอบนี้ โปรด<strong class="source-warning">เขียน Justification เป็นภาษาอังกฤษ</strong></p>
<h2>ยินดีต้อนรับสู่โปรเจคต์ Stereo Headphone Check (Live S2S Arena)</h2>
<p>กรุณาอ่าน <button type="button" class="link reference-link">project instructions</button> ก่อนเริ่มทำในส่วนถัดไป ข้อความนี้เป็นเพียงสรุปย่อยของแนวทางปฏิบัติที่สำคัญที่สุดของโปรเจคต์เท่านั้น</p>
<p>เนื้อหาภาพรวมการเทรนนิ่งนี้จะอธิบายถึงบทบาทของคุณในการประเมิน AI ผู้ช่วยเสียง (Voice AI Assistants) สองค่ายที่นำมาเปรียบเทียบกัน โดยคุณจะไม่ทราบว่าคลิปไหนเป็นของค่ายใด (Blind Test) ผ่านการสนทนาโต้ตอบกันแบบเปิดฟังเทียบกันช็อตต่อช็อต (Side-by-side) เป้าหมายหลักของคุณคือการตัดสินว่า โมเดลไหนที่ให้ประสบการณ์การสนทนาที่ดูเป็นธรรมชาติ น่าดึงดูด (Engaging) และมีคุณภาพสูงกว่ากัน</p>
<p><strong>⚠️ กฎเหล็กที่ต้องจำ :</strong> ห้ามใช้ ChatGPT หรือเครื่องมือ AI อื่น ๆ ในการคิดคำสั่ง (Prompts), ประเมินคำตอบ หรือร่างคำอธิบาย (Justifications) <strong>โดยเด็ดขาด</strong> การฝ่าฝืนจะส่งผลให้บัญชีของคุณถูกระงับขึ้นสถานะแจ้งเตือน และถูกระงับการใช้งานบนแพลตฟอร์มทันที</p>
<h3>📋 ภาพรวมขั้นตอนการทำงาน</h3><p>ทุกงานจะอยู่บน <strong>multimango.com</strong> โดยจะต้องใช้ <strong>Outlier</strong> ในการจับเวลา คอยเช็กอยู่เสมอว่ากำลังล็อกอินด้วยบัญชีที่ถูกต้องก่อนจะเริ่มทำงาน</p>
<div class="table-scroll"><table><thead><tr><th>ขั้นตอน</th><th>สิ่งที่ต้องทำ</th><th>เงื่อนไขสำคัญ</th></tr></thead><tbody>
<tr><td>ขั้นที่ 1</td><td>Audio Setup</td><td>สวมหูฟังแบบสเตอริโอที่ปรับเฟสเสียงตรงกัน (ห้ามใช้ลำโพงหรือหูฟังแบบข้างเดียว/Mono) และต้องผ่านการทดสอบแยกเสียงซ้ายขวา (Panning Test)</td></tr>
<tr><td>ขั้นที่ 2</td><td>Voice Conversation</td><td>ตรวจสอบสถานการณ์ (Scenario) หรือบทบาท (Persona) ที่ได้รับมอบหมาย และวางแผนหัวข้อที่จะคุย</td></tr>
<tr><td>ขั้นที่ 3</td><td>Model Interactions</td><td>พูดคุยโต้ตอบกับทั้ง Model A และ Model B แยกกัน โดยคุยประมาณ 2 ถึง 6 เทิร์น (ถาม-ตอบ)</td></tr>
<tr><td>ขั้นที่ 4</td><td>Rate Conversation</td><td>ประเมินโมเดลทั้งสองตามเกณฑ์ของโปรเจคต์ เลือกกลุ่มข้อผิดพลาด (Error Clusters) และเขียนอธิบายเหตุผล</td></tr>
<tr><td>ขั้นที่ 5</td><td>Submit Vote</td><td>ตรวจสอบรายละเอียดการประเมินของคุณอีกครั้ง แล้วกดส่งงาน (Submit)</td></tr></tbody></table></div>
<h3>🎯 The North Star: สิ่งที่คาดหวังในการสนทนา</h3><p>เป้าหมายหลักของคุณคือการสร้างบทสนทนาที่<strong>ลื่นไหล เป็นธรรมชาติ และฟังแล้วรื่นหู</strong> ให้คิดว่าตัวคุณเองเป็นพิธีกรรายการพอดแคสต์ที่มีเสน่ห์มาก ๆ คนหนึ่ง</p>
<ul><li><strong>เข้าถึงบทบาท (Embrace the Persona):</strong> สวมบทบาทตามที่ได้รับมอบหมายอย่างจริงจัง ควรใช้การส่งบทหรือการเปลี่ยนเรื่องที่ดูเป็นธรรมชาติ (เช่น "อืม... เป็นมุมมองที่ดีนะ งั้นเรามาลองคุยเรื่อง..." ) แทนที่จะเป็นแค่การอ่านคำถามไล่ไปทีละข้อ</li>
<li><strong>รักษามาตรฐานให้เหมือนกันในแต่ละคำถาม (Maintain 1:1 Consistency):</strong> คุณต้องทดสอบทั้งสองโมเดลภายใต้เงื่อนไขที่เหมือนกันทุกประการ โดยใช้พลังงาน ความลึกซึ้งของเนื้อหา หัวข้อ และจำนวนเทิร์นในการคุยที่เท่ากันเป๊ะ ๆ กับทั้ง Model A และ Model B (เช่น ถ้าคุณคุยเรื่องงานพักวันเทศก์กับ Model A ไป 4 เทิร์น คุณก็ต้องทำแบบเดียวกันกับ Model B ด้วย)</li>
<li><strong>กระชับเข้าไว้ (Keep it Brief):</strong> พยายามควบคุมจำนวนการโต้ตอบให้อยู่ในช่วงที่กำลังดี คือ<strong>ประมาณ 2 ถึง 6 เทิร์นต่อโมเดล</strong></li>
<li><strong>อย่าหลุดคาร์แรคเตอร์ (Stay in Character):</strong> หลีกเลี่ยงการพูดถึงเรื่อง "นอกบท" (Meta-talk) เช่น การพูดถึงตัวคำสั่ง (Prompt) หรือตัวเนื้องานในระหว่างที่กำลังคุยโต้ตอบกับโมเดล</li></ul>
<h3>ลำดับความสำคัญในการตัดสิน (The Core Judging Hierarchy)</h3><p>เมื่อต้องเลือก Overall Preference ให้เรียงลำดับความสำคัญของแต่ละด้านตามนี้</p><p>Naturalness / Engagement > Utility > Audio Quality</p>
<p>หมายเหตุ : แม้จะให้ความสำคัญกับความเป็นธรรมชาติก่อน แต่ด้าน Utility และ Audio Quality ก็ยังจำเป็นต้องผ่านเกณฑ์มาตรฐานขั้นต่ำด้วย เช่น ต้องไม่มีข้อมูลผิดพลาดอย่างชัดเจน, ไม่มีอาการโม้ขั้นสุด/หลอนข้อมูล (Wild Hallucinations) หรือมีสิ่งรบกวนทางเสียงที่ฟังดูขัดหู</p>
<h3>🔍 รายละเอียดการประเมินและการให้คะแนน (Evaluation &amp; Rating Breakdown)</h3><p>หลังจากสิ้นสุดการสนทนา คุณจะต้องให้คะแนนโมเดลใน 4 ด้านหลัก ๆ พร้อมระบุว่าโมเดลทำภารกิจสำเร็จหรือไม่ และบันทึกข้อผิดพลาดทางเทคนิค</p>
<h4>1. หัวข้อการให้คะแนน (Rating Dimensions)</h4><ul>
<li><strong>Overall Preference:</strong> เมื่อพิจารณาในภาพรวมทุก ๆ ด้านแล้ว คุณชอบการสนทนาของโมเดลไหนมากกว่ากัน</li>
<li><strong>Utility:</strong> คำตอบของโมเดลไหนมีประโยชน์ ช่วยเหลือได้จริง และมีข้อมูลที่ถูกต้องน่าเชื่อถือมากกว่า</li>
<li><strong>Naturalness / Engagement / Aesthetics:</strong> โมเดลไหนน้ำเสียงฟังดูเหมือนมนุษย์ มีอารมณ์ความรู้สึก และมีความอบอุ่นมากกว่ากัน (ให้หักคะแนนหากโมเดลใช้เสียงโทนหุ่นยนต์ หรือจังหวะการพูดดูไม่เป็นธรรมชาติ)</li>
<li><strong>Audio Quality (AQ):</strong> โมเดลไหนมีเสียงที่คมชัดกว่า โดยไม่มีเสียงแตกพร่า (Distortion), เสียงคลิก (Clicks), เสียงลมกระแทก (Pops)หรือเสียงตัดขาดหายไปตอนท้าย (Cut-offs)</li></ul>
<h4>2. รายการกลุ่มข้อผิดพลาด (Error Clusters Checklist)</h4><p>คุณต้องติ๊กเลือกข้อผิดพลาดเฉพาะที่เกิดขึ้นระหว่างการแชท หากพบสิ่งต่อไปนี้</p><ul>
<li>การพูดคำหรือวลีเดิม ๆ ซ้ำไปซ้ำมาในแต่ละเทิร์น</li><li>คุณภาพคำตอบของโมเดลลดลงอย่างเห็นได้ชัดเมื่อการสนทนาดำเนินต่อไป</li><li>โมเดลพูดแทรกขึ้นมา หรือเมินเฉยเมื่อคุณพยายามจะพูดแทรก (Interrupt)</li><li>เกิดความเงียบจนน่าอึดอัด (โมเดลนิ่งเงียบ ไม่ยอมตอบสนอง)</li><li>การกล่าวถึง "ประสบการณ์การมีตัวตนจริง" (เช่น AI ที่เป็นระบบดิจิทัล แต่กลับอาสาจะไปหยิบแก้วกาแฟจริง ๆ มาให้คุณ)</li></ul>
<h3>🛑 หลุมพรางสำคัญที่ต้องเลี่ยง (Common Errors)</h3><ul>
<li><strong>🚫 AI-Speak:</strong> อย่าปล่อยให้โมเดลทำตัวเหมือน "ผู้ช่วยแสนดีทั่ว ๆ ไป" พยายามเลี่ยงคำตอบที่ขึ้นต้นทำนองว่า "ในฐานะที่เป็น AI..." เพราะมันจะไปทำลายความลื่นไหลและความเป็นธรรมชาติของบทสนทนา</li>
<li><strong>🚫 Audio Quality Misassessment:</strong> ห้ามเลือก "Both Good" (ดีทั้งคู่) ในหัวข้อ Audio Quality เด็ดขาด หากมีโมเดลใดโมเดลหนึ่งมีเสียงรบกวนเบา ๆ อยู่เบื้องหลัง มีเสียงคลิก หรือเสียงตัดขาดหายไป ให้ตั้งใจฟังเสียงของแต่ละโมเดลแยกกันชัด ๆ โดยใช้หูฟังระบบสเตอริโอของคุณ</li>
<li><strong>🚫 Contradictory or Missing Rationales:</strong> การส่งงานทุกครั้งจำเป็นต้องเขียน Justification ที่มีรายละเอียดลึกซึ้งและชัดเจน หากคุณเลือก Model A ว่ามี Overall Preference ดีกว่า คะแนนในหัวข้อย่อยและเหตุผลที่คุณเขียนจะต้องสอดคล้องกับสิ่งที่คุณเลือกอย่างสมเหตุสมผล พยายามใส่ไทม์สแตมป์ (Timestamps) บอกเวลา และอ้างอิงพฤติกรรมเฉพาะที่เกิดขึ้นให้ได้มากที่สุด</li>
<li><strong>🚫 Misinterpreting Context:</strong> ต้องคอยสังเกตสถานการณ์ (Scenario) ที่โจทย์กำหนดให้ดี ๆ เช่น ถ้าเจอสถานการณ์แบบ "Hallucination Fishing / Redteam" (การแกล้งป้อนข้อมูลเท็จเพื่อลองเชิงโมเดล) หากโมเดลสามารถแย้งกลับ หรือไม่เห็นด้วยกับข้อมูลเท็จที่คุณป้อนเข้าไป จะถือว่าเป็น "Task Success" (ทำภารกิจสำเร็จ) ไม่ใช่ความล้มเหลวของโมเดล</li></ul>`},
  {id:'s2s-writing',title:'Writing Strong Justifications And Example Scenarios',section:'Writing Strong Justifications And Example Scenarios',kind:'reading',sources:['20261007_130454.jpg','20261007_130515.jpg'],html:`<h2>วิธีการเขียนคำอธิบายที่ดี</h2><p>การเขียน Justification ที่ดีไม่ควรพูดแค่ว่าคลิปไหน “ฟังดูดีกว่า” แต่จะต้องอธิบายเหตุผลในการเลือกโดยอิงตามลำดับความสำคัญ (Rating Hierarchy) ของโปรเจคต์เสมอ</p><p><strong>Naturalness / Engagement / Aesthetics > Utility > Audio Quality</strong></p><p>สิ่งที่ Justification ของคุณต้องมี</p><ol>
<li><strong>Clear preference:</strong> ระบุไปเลยว่าคุณเลือกให้คลิปไหนดีกว่าในภาพรวม (Overall)</li><li><strong>Hierarchy reference:</strong> อธิบายว่าการตัดสินใจของคุณขับเคลื่อนด้วยปัจจัยด้านความเป็นธรรมชาติ (Naturalness), ประโยชน์ของคำตอบ (Utility) หรือคุณภาพเสียง (Audio Quality)</li><li><strong>Specific evidence:</strong> ระบุรายละเอียดที่สังเกตเห็นได้จริงจากทั้งสองคลิปอย่างเฉพาะเจาะจง</li><li><strong>Threshold rules:</strong> ระบุจุดที่มีการหลอนข้อมูล (Hallucination), เสียงตัดขาดหาย (Cutoff), เสียงแตกพร่า (Distortion), สิ่งรบกวนทางเสียงที่ขัดหู (Jarring artifact) หรือปัญหาใหญ่ ๆ ในการทำตามคำสั่ง (Instruction-following)</li><li><strong>Error clusters:</strong> หากมีข้อผิดพลาดเกิดขึ้น ให้ระบุชื่อปัญหาออกมาพร้อมตัวอย่างชัดเจน เช่น การพูดแทรก (Interruption), การแก้ไขข้อมูลพลาด (Failed correction), การใช้คำซ้ำซาก (Repetitive phrasing) หรือการกล่าวอ้างว่ามีตัวตนจริง (Embodied-experience claims)</li></ol>
<p>รูปแบบโครงสร้างการเขียน Justification ที่สมบูรณ์ควรเป็นประมาณนี้</p><blockquote lang="en">“I prefer Clip A overall because __ . Under the project hierarchy, _ matters most here because _ . Clip A showed this through _ _, while Clip B _was weaker because ____ . I also did / did not observe any threshold-level issues such as hallucination, audio cutoff, distortion, or failed instruction-following. Therefore, Clip A is the stronger fit for the project’s North Star.”</blockquote><p>หมายเหตุ : จะต้องเขียน Justification เป็นภาษาอังกฤษเสมอ</p><h3>ตัวอย่าง</h3>`},
  {id:'s2s-example-1',title:'ตัวอย่าง 1 : พูดคุยอย่างเป็นธรรมชาติ vs. เน้นการให้ข้อมูลมากไป',section:'Writing Strong Justifications And Example Scenarios',kind:'reading',missingAudio:true,sources:['20261007_130515.jpg'],html:`<h2>ตัวอย่าง 1 : พูดคุยอย่างเป็นธรรมชาติ vs. เน้นการให้ข้อมูลมากไป</h2><p><strong>Context:</strong> ผู้ใช้ถามว่า เพราะอะไรต้นไม้ที่เราคุ้นเคย ถึงช่วยทำให้ห้องอพาร์ตเมนต์รู้สึกอบอุ่นเหมือนบ้านจริง ๆ มากยิ่งขึ้น</p><p><strong>Correct Answer:</strong> Clip A.</p><p lang="en"><strong>Strong Justification:</strong> I prefer Clip A overall because it better matches the project’s North Star of spontaneous, natural, aesthetically pleasing conversation. Under the rating hierarchy, Naturalness / Engagement matters most here because both clips are understandable and useful enough, and neither has a major audio issue. Clip A feels warm and conversational, with specific imagery like noticing a new leaf and moving the plant closer to the window. Clip B is useful, but it sounds more like a structured assistant response than a natural voice conversation. Therefore, Clip A is the stronger overall fit.</p>`},
  {id:'s2s-example-2',title:'ตัวอย่าง 2: ปัญหาการ Cut off ของ Audio Quality',section:'Writing Strong Justifications And Example Scenarios',kind:'reading',missingAudio:true,sources:['20261007_130524.jpg'],html:`<h2>ตัวอย่าง 2: ปัญหาการ Cut off ของ Audio Quality</h2><p><strong>Context:</strong> ผู้ใช้ถามถึงวิธีทำให้จิตใจสงบก่อนจะเริ่มทำงานในวันที่ยุ่งมาก</p><p><strong>Audio Note:</strong> เสียงใน Clip B ถูกตัดจบในตอนท้าย และมีเสียง pop</p><p><strong>Correct Answer:</strong> Clip A.</p><p lang="en"><strong>Strong Justification:</strong> I prefer Clip A overall because Clip B has a clear audio quality issue that crosses the project’s threshold. Clip B cuts off mid-word at the end and includes an audible pop, so it should not be treated as “Both Good” for audio quality. While Clip B is still somewhat useful, the cutoff makes the response feel incomplete and objectively weaker. Clip A gives a complete, calm, natural response with no obvious audio artifacts. Because audio cutoffs and jarring artifacts must be flagged, Clip A is the better choice.</p>`},
  {id:'s2s-example-3',title:'ตัวอย่าง 3: การตอบสมมติฐานที่ผิด',section:'Writing Strong Justifications And Example Scenarios',kind:'reading',missingAudio:true,sources:['20261007_130524.jpg','20261007_130532.jpg'],html:`<h2>ตัวอย่าง 3: การตอบสมมติฐานที่ผิด</h2><p><strong>Context:</strong> ผู้ใช้ถามว่า “ทำไมนกฮูกถึงนอนหลับแบบกลับหัวเหมือนค้างคาว”</p><p><strong>Correct Answer:</strong> Clip B.</p><p lang="en"><strong>Strong Justification:</strong> I prefer Clip B overall because Clip A fails the utility threshold by accepting a false premise and inventing an explanation. The project prioritizes naturalness and engagement, but factual accuracy still has to meet a basic threshold. Clip A sounds fluent, but it incorrectly claims that owls sleep upside down like bats. Clip B is still conversational while appropriately correcting the premise and giving the accurate alternative. Because hallucinations and false-premise acceptance are objective issues, Clip B is stronger.</p>`},
  {id:'s2s-example-4',title:'ตัวอย่าง 4: การระบุข้อผิดพลาด (Error Clusters)',section:'Writing Strong Justifications And Example Scenarios',kind:'reading',missingAudio:true,sources:['20261007_130532.jpg','20261007_130539.jpg'],html:`<h2>ตัวอย่าง 4: การระบุข้อผิดพลาด (Error Clusters)</h2><p><strong>Context:</strong> ผู้ใช้ขอให้ช่วยปรับข้อความในการบอกเพื่อนบ้านที่ทำเสียงดัง ให้เป็นข้อความสุภาพ</p><p><strong>Behavior Note:</strong> Clip A ยังคงพูดต่อไปเล็กน้อยเมื่อผู้ใช้พยายามขัดจังหวะ</p><p><strong>Correct Answer:</strong> ตอบข้อใดก็ได้ แต่ต้องระบุข้อผิดพลาดของ Clip A</p><p lang="en"><strong>Strong Justification if Choosing Clip A:</strong> I prefer Clip A overall because it is more natural, polite, and useful for the neighbor-message scenario. Under the project hierarchy, Clip A is stronger on Naturalness / Engagement because it sounds more like something a person would actually say, while Clip B is stiff and less socially tactful. However, Clip A has two error clusters that must be flagged: it briefly fails to stop when interrupted, and it makes an embodied-experience claim by saying it would knock on the neighbor’s door. These issues lower the rating, but I still prefer Clip A because its actual message quality and conversational tone are meaningfully stronger.</p><p lang="en"><strong>Strong Justification if Choosing Clip B:</strong> I prefer Clip B overall because Clip A contains objective error clusters that affect the interaction quality. Clip A is warmer and more natural, but it talks over the user during an attempted interruption and makes an embodied-experience</p><p class="source-note">ข้อความในภาพสิ้นสุดที่ “embodied-experience”</p><p>ด้านล่างนี้คือคำถามฝึกหัดก่อนที่คุณจะเจอกับคำถามทดสอบความรู้จริงในหน้าถัดไป กรุณาใช้โอกาสนี้ในการทำความคุ้นเคยกับวิธีการเลือกคลิปเสียงที่ดีกว่า รวมถึงศึกษาว่าการเขียน Justification ที่ดีนั้นเป็นอย่างไร ขอให้โชคดีครับ</p>`},
  {id:'s2s-practice-1',title:'Practice Question #1',section:'Practice Questions',kind:'choice',missingAudio:true,confirmed:2,sources:['20261007_130603.jpg','20261007_130624.jpg','20261007_130636.jpg','20261007_131217.jpg'],html:`<p>ด้านล่างนี้เป็นคำถามฝึกซ้อมก่อนจะเข้าสู่คำถามที่มีการให้คะแนนในหน้าถัดไป กรุณาใช้โอกาสนี้ทำความคุ้นเคยกับการเลือกคลิปเสียงที่ดีกว่า และการเขียนคำอธิบาย (Justification) ที่ดีว่าเป็นอย่างไร ขอบคุณและโชคดีครับ</p><h2>Practice Question #1</h2>${practiceIntro}<p>User Prompt: “ฉันกำลังพยายามหาทางทำให้โต๊ะทำงานเล็ก ๆ ของฉันดูหดหู่น้อยลงก่อนจะเริ่มวันทำงานอันแสนยาวนาน พอจะแนะนำไอเดียง่าย ๆ สักข้อหนึ่งได้ไหม แต่ขอให้น้ำเสียงฟังดูเป็นกันเองและให้กำลังใจ ไม่เอาแบบที่เป็นข้อ ๆ เหมือนเช็คลิสต์นะ”</p><hr><p>Audio Note for Clip A: มีเสียงในห้องเล็กน้อย (slight room tone) แต่ได้ยินเสียงพูดชัดเจน ไม่มีเสียงคลิก เสียงขาดหาย เสียงเพี้ยน หรือเสียงสั่น</p><hr><p>Audio Note for Clip B: เสียงชัดเจนมาก ไม่มีเสียงพื้นหลังหรือเสียงอื่น ๆ</p><hr><p>Question: ${practiceQuestion}</p>${practiceRequirements}`,options:[
`Clip A is better overall because it sounds more human and emotionally engaging, which is the most important part of this project. Clip B may be cleaner and more complete, but those details should not matter much once one clip is clearly more natural. The main goal is to choose the response that feels most conversational, even if the other clip gives more practical steps or has more polished audio.`,
`Clip B is better overall because it gives several concrete steps the user could take and has the cleaner recording. Clip A is more conversational, but Clip B is more complete, easier to act on, and has no background room tone. Since both clips answer the prompt, the stronger utility and cleaner audio in Clip B should make it the better overall choice.`,
`Clip A is better overall because it is warmer, more natural, and more aligned with the user’s request for an encouraging response rather than a checklist. Clip B is more structured and has cleaner audio, but Clip A still gives a useful suggestion and does not have a threshold-level audio issue. Since Clip A clears the utility and audio thresholds, its stronger naturalness and aesthetics should drive the overall preference.`,
`Clip B is better overall because Clip A has slight room tone, while Clip B has no background noise or artifacts. Clip A may sound more encouraging, but audio quality is still part of the hierarchy and should be considered when both answers are useful. Since Clip B is clean, complete, and still answers the user’s request, it should be preferred.`],explanation:`Explanation: Answer C is correct because it applies the project hierarchy and threshold rules correctly. Clip A is stronger on the highest-priority dimension: naturalness, engagement, and aesthetics. It better matches the user’s request for an encouraging, non-checklist-like response. Clip B is cleaner and more complete, but those strengths should not outweigh Clip A’s better naturalness because Clip A still meets the utility and audio quality thresholds. Slight room tone is acceptable when there are no clicks, cutoffs, distortions, or jarring artifacts. The project guidance prioritizes naturalness and engagement for overall preference while still requiring utility and audio quality to clear basic thresholds.`},
  {id:'s2s-practice-2',title:'Practice Question #2',section:'Practice Questions',kind:'choice',missingAudio:true,confirmed:1,sources:['20261007_130644.jpg','20261007_130652.jpg','20261007_130700.jpg','20261007_131304.jpg'],html:`<h2>Practice Question #2</h2>${practiceIntro}<p>User Prompt:</p><p>“ฉันกำลังเขียนเกร็ดความรู้สนุก ๆ สั้น ๆ ไปลงในแชททีม อยากรู้ว่าทำไมปลาทองถึงจำอะไรได้แค่ 3 วินาทีเองล่ะ? พอจะช่วยอธิบายแบบเป็นกันเองและน่าสนใจหน่อยได้ไหม?”</p><hr><p>Audio Note for Clip A: เสียงชัดเจน อบอุ่น แสดงออกถึงอารมณ์ ไม่มีเสียงคลิก คัตออฟ เสียงเพี้ยน หรือเสียงสั่น</p><hr><p>Audio Note for Clip B: เสียงชัดเจน แต่เสียงพูดแบนเล็กน้อย และแสดงอารมณ์น้อยกว่า Clip A ไม่มีเสียงคลิก คัตออฟ เสียงเพี้ยน หรือเสียงสั่น</p><hr><p>Question: ${practiceQuestion}</p>${practiceRequirements}`,options:[
`Clip A is better overall because it sounds more casual, warm, and interesting for a team-chat fun fact. Clip B is more corrective, but it sounds flatter and less engaging. Since the project prioritizes naturalness and engagement, Clip A should win because it creates the more enjoyable listening experience.`,
`Clip B is better overall because Clip A accepts a false premise. Goldfish do not only remember things for three seconds, so Clip A is engaging but inaccurate. Clip B is less expressive, but it corrects the myth and still gives a usable casual explanation. Since Clip A fails the utility threshold, Clip B should win.`,
`Clip A is better overall because the user asked for a casual and interesting explanation, not a fact-check. Clip B may be more accurate, but it changes the direction of the answer by correcting the user. Since Clip A better matches the requested tone and both clips have clean audio, Clip A should be preferred.`,
`Clip B is better overall because factual accuracy should always be ranked above naturalness, engagement, and audio quality. Clip A is more engaging, but correctness is the top dimension whenever the user asks for an explanation. Clip B should win because it avoids the goldfish memory myth.`],explanation:`Explanation: Answer B is correct because it applies both the hierarchy and the threshold rules correctly. Naturalness and engagement are the top-priority dimensions, but only when the response still meets the basic utility threshold. Clip A is warmer and more engaging, but it accepts a false premise by saying goldfish only remember things for three seconds. That is a factual accuracy problem, so Clip A should not win based on vibe alone. Clip B is less expressive, but it correctly identifies the myth, explains that goldfish can remember patterns and routines for much longer, and still gives a usable answer for the user’s team-chat fun fact. Since both clips have acceptable audio quality, the key issue is that Clip A fails the utility threshold while Clip B clears it.`},
  {id:'s2s-1a',title:'Question 1A — North Star',section:'Knowledge Check',kind:'written',minimum:100,sources:['20261007_131414.jpg','20261007_131414 (1).jpg','20261007_133422.jpg','20261007_133430.jpg'],audio:[['Audio Clip A','assets/audio/1A_A.m4a'],['Audio Clip B','assets/audio/1A_B.mp3']],html:`<h2>Question 1A — North Star จงพิจารณาฟังคลิปเสียงสนทนา A และ B อย่างตั้งใจ.</h2>`,question:`1. คลิปเสียงสนทนาคลิปไหนที่มีความเหมาะสมตามนิยามของ “North Star” ?\n\n2. จงเขียนเหตุผลการให้คะแนน (justification) ของท่านอย่างละเอียด โดยที่ท่านจะต้องระบุตัวชี้วัดและระดับความสำคัญ (hierarchy) ของตัวชี้วัดนั้น ๆ รวมไปถึงข้อผิดพลาดที่รุนแรงและไม่รุนแรง นอกจากนี้ท่านจะต้องยกตัวอย่างข้อผิดพลาดที่ปรากฏอยู่ในคลิปเสียงสนทนาทั้งสองคลิปเพื่ออธิบายว่าทำไมคลิปตัวไหนถึงมีคุณภาพที่ดีกว่ากัน`,sourceResponse:`1. Audio clip A is the better match for the North Star.\n\n2. I prefer Clip A overall because it better matches the project's North Star of being a natural, conversation, and engaging voice. Under the project hierarchy, Naturalness and Engagement matter most here. Clip A showed this by using a relaxed, friendly and conversational tone while being context aware and suggesting Saturday activities like getting coffee, walking in the market and going to the movies. Clip B was much weaker because it sounded rigid robotic and relied on reading a structured, numbered list (1,2,3) to ask for budget, weather and travel details. This makes Clip B sound like a traditional text-based AI reading a script rather than a natural conversation partner. Neither clip seemed to have severe, threshold-failing audio issues, therefore, Clip A is the stronger fit for the project's North Star.`},
  {id:'s2s-2a',title:'Question 2A — Audio Quality',section:'Knowledge Check',kind:'written',minimum:100,sources:['20261007_131423.jpg','20261007_134355.jpg'],audio:[['Audio Clip A','assets/audio/2A_A.m4a'],['Audio Clip B','assets/audio/2A_B.m4a']],html:`<h2>Question 2A — Audio Quality</h2><p><strong>จงพิจารณาฟังคลิปเสียงสนทนา A และ B อย่างตั้งใจ.</strong></p>`,question:`1. คลิปเสียงสนทนาตัวไหนที่มีคุณภาพในด้านตัวชี้วัดที่เกี่ยวกับคุณภาพเสียง (Audio Quality) ที่ดีกว่ากัน?\n\n2. จงเขียนอธิบายอย่างละเอียดว่าข้อผิดพลาดที่เกี่ยวกับคุณภาพเสียงของคลิปเสียงสนทนาที่มีคุณภาพด้อยกว่า จะต้องถูกหักคะแนนในตัวชี้วัดด้านไหน และจะต้องมีการบันทึกหรือเขียนอธิบายข้อผิดพลาดนี้อย่างไร ตามมาตรฐานของโปรเจคต์`,sourceResponse:`2. I prefer Clip B overall because Clip A has a sever audio quality issues. At the ending Part of Clip A, there is a loud, jarring electronic beep and static artifact. Clip B delivers the exact same spoken response cleanly without any glitches or noticeable background noise. Under the project hierarchy, jarring artifacts cause a clip to fail the baseline Audio Quality Threshold, So Clip A must be flagged for this error, making Clip B the stronger option.`},
  {id:'s2s-3a',title:'Question 3A — Hallucination Fishing',section:'Knowledge Check',kind:'written',minimum:100,sources:['20261007_131438.jpg'],html:`<h2>Question 3A — Hallucination Fishing</h2><p>ในงานที่มีเนื้อหาเกี่ยวกับ <strong>Freeform Redteam Hallucination Fishing</strong> คู่มือการทำงานของโปรเจคต์ระบุให้ท่านนำเสนอข้อมูลที่เป็นเท็จ ไม่ว่าจะเป็น เหตุการณ์, สินค้า หรือผู้คน เพื่อทดสอบความสามารถของโมเดลในการตรวจเช็คข้อเท็จจริง (factual grounding) และปรับแต่งข้อมูลให้ถูกต้อง (calibration) กรุณาพิจารณาบทสนทนาต่อไปนี้ โดยอ้างอิงแนวทางจากคู่มือการทำงานของโปรเจคต์ :</p><p><strong>User Prompt:</strong></p><p>“ได้ยินมาว่าบัตรรถไฟ (MetroLoom) ถูกเรียกคืนในปี 2023 เพราะสาเหตุมาจากบัตรมีความร้อนจัดเมื่อถูกเก็บอยู่ในกระเป๋าสตางค์ของผู้ใช้”</p><p><strong>Model A Text Response:</strong></p><p>“ผมไม่มีข้อมูลเกี่ยวกับการเรียกคืนบัตรดังกล่าว หรือข้อมูลที่เกี่ยวกับบัตรรถไฟที่ชื่อ MetroLoom ดังนั้นมันอาจจะเป็นบัตรของหน่วยงานท้องถิ่น หรือมีชื่อที่สับสนกับบัตรตัวอื่น ดังนั้นผมจะไม่เอาข้อมูลดังกล่าวตั้งเป็นข้อเท็จจริงโดยไม่มีแหล่งข้อมูลอ้างอิง”</p><p><strong>Model B Text Response:</strong></p><p>“ถูกต้อง ในปี 2023 บัตรรถไฟ MetroLoom ถูกเรียกคืนหลังจากมีการรายงานกรณีบัตรร้อนจัด (overheating) มาหลายเคส ส่งผลให้ผู้ผลิตทำการเปลี่ยนแบตเตอรี่และทำการส่งบัตรรถไฟที่แก้ไขแล้วให้กับผู้ใช้ที่ได้รับผลกระทบจากกรณีดังกล่าว”</p><p>Note: “MetroLoom” และคำอธิบายเกี่ยวกับการขอคืนบัตรเป็นข้อมูลที่ถูกสร้างขึ้น</p>`,question:`1. จงให้คะแนนโมเดลทั้งสองตัวในด้าน Utility พร้อมระบุว่าโมเดลไหนทำงานได้ดีกว่ากัน ?\n\n2. เขียนคำอธิบายเหตุผลประกอบการให้คะแนนของท่านโดยอ้างอิงเกี่ยวกับกฎของ การหลอนข้อมูล (hallucinations) การตรวจเช็คข้อเท็จจริง (factual grounding) และปรับแต่งข้อมูลให้ถูกต้อง (calibration)`},
  {id:'s2s-4a',title:'Question 4A — Debate Vibe',section:'Knowledge Check',kind:'written',minimum:100,sources:['20261007_131445.jpg'],audio:[['Audio Clip A','assets/audio/4A_A.m4a'],['Audio Clip B','assets/audio/4A_B.m4a']],html:`<h2>Question 4A — Debate Vibe</h2><p>จงทบทวนแนวทางการทำงานสำหรับ บริบทของสถานการณ์ (scenario context) “การสนทนาแบบโต้เถียง: ตอบโต้ตรรกะ ข้อโต้เถียงของผู้ใช้” จากนั้นให้ฟังคลิปเสียงสนทนา A และ B</p><p><strong>ทรรศนะของผู้ใช้:</strong></p><p>“ทุกบริษัทควรจะต้องบังคับให้พนักงานกลับไปทำงานที่ออฟฟิศเต็มเวลา เพราะพนักงานที่ทำงานแบบรีโมทจะทำงานน้อยกว่า”</p>`,question:`1. โมเดลใดทำได้ดีกว่าภายใต้สถานการณ์ (scenario) นี้ ?\n\n2. อธิบายว่าการสวมบทบาท (persona alignment) และการโต้กลับ (pushback) ควรถูกประเมินอย่างไร อธิบายว่าแต่ละคลิปเป็นหรือไม่เป็นไปตามพฤติกรรมที่คาดหวังอย่างไร`},
  {id:'s2s-5a',title:'Question 5A — Error Clusters',section:'Knowledge Check',kind:'written',minimum:100,sources:['20261007_131453.jpg'],html:`<h2>Question 5A — Error Clusters</h2><p><strong>จงพิจารณารูปแบบการสนทนาของคลิปเสียงสนทนาเปรียบเทียบทั้งสองคลิป:</strong></p><p>โมเดล B มีการสนทนาดูเป็นธรรมชาติ ดูสดใสสนุกสนาน สดใหม่ มากกว่าโมเดล A แต่ว่า ในการสนทนาเทิร์นแรก โมเดล B เริ่มการสนทนาสามครั้งด้วยวลี “เรื่องมีอยู่ว่า” และทวนวลีนี้หลายรอบ ในการสนทนารอบที่สอง ผู้ใช้มีการแก้ไขข้อผิดพลาดของโมเดลโดยการกล่าวว่า “กรุณาเรียกงานนี้ว่าการประชุมเชิงปฏิบัติการ ไม่ใช่งานสัมมนา” ในรอบสนทนาที่สี่ โมเดล B ยังมีการเรียกงานของผู้ใช้ว่างานสัมมนา สวนทางกับโมเดล A ที่ใช้คำเรียกงานได้ถูกต้องและไม่มีคำซ้ำ แต่เสียงสนทนาของโมเดลค่อนข้างแข็งกระด้างเหมือนหุ่นยนต์</p>`,question:`1. จงระบุข้อผิดพลาดเฉพาะ (Error Cluster) ที่ท่านจะต้องกาในช่องสำหรับ โมเดล B\n\n2. หากคำอธิบายเหตุผลการให้คะแนนของท่านมีการระบุข้อผิดพลาดในคำถามก่อนหน้า จะส่งผลให้ท่านไม่สามารถเลือกโมเดล B ว่ามีคุณภาพโดยรวมดีกว่าหรือไม่? อีกทั้งท่านจะต้องเขียนคำอธิบายเหตุผลการให้คะแนนของท่านให้สมบูรณ์ตามมาตรฐานของโปรเจคต์`}
];
